#!/bin/bash

# a lazy guy's wrapper for apt commands

case $1 in
    # short-cuts
    s)    shift; set -x; apt-cache search "$@";;
    i)    shift; set -x; apt-get install "$@";;
    u)    shift; set -x; apt-get update "$@";;
    dep)  shift; set -x; apt-cache depends "$@";;
    rdep) shift; set -x; apt-cache rdepends "$@";;
    # apt-cache
    showpkg|showsrc|stats|search|show|depends|rdepends|pkgnames)
        set -x
        apt-cache "$@"
        ;;
    # apt-get
    update|upgrade|install|remove|purge|source|check|download|clean|autoclean|autoremove|uninstall)
        set -x
        sudo apt-get "$@"
        ;;
    get|cache)
        aptcmd="apt-$1"
        shift
        $aptcmd "$@"
        ;;
    ''|-h|--help)
        echo "Usage: apt {Commands for apt-get or apt-cache}"
        ;;
    *)
        echo "ERROR: unsupported apt-(get|cache) command for this wrapper: $1"
        exit 1
        ;;
esac
