#!/bin/bash
#
# ping, portping on ssh, ssh, and then check fs status.
#

set -ue

ssh () {
    batch-ssh "$@"
}

my_ping () {
    ping -w 4 -c 1t $1 >/dev/null 2>&1
}

my_sshping () {
    portping $1 >/dev/null 2>&1
}

my_sshtest () {
    ssh $1 /bin/true
}

my_fstest () {
    # ext3/4 mounted readonly probably means fs or disk fault.
    if ret=$(ssh $1 "grep 'ext[34] .*\<ro\>' /proc/mounts")
    then
        echo "$ret"
        return 1
    else
        return 0
    fi
}

run_all_pings () {
    echo -n "$1: "
    if ! my_ping $1
    then
        echo "FAIL: Ping failed"
        return 1
    elif [ "$opt_portping" != 'yes' ] && ! my_sshping $1
    then
        echo "FAIL: SSH port is not open (ping OK)"
        return 1
    elif ! my_sshtest $1
    then
        echo "FAIL: SSH login with -o BatchMode=yes failed (ssh port open)"
        return 1
    elif ! ret=$(my_fstest $1)
    then
        echo "FAIL: There's readonly ext3 filesystem: ${ret%% *} (login OK)"
        return 1
    else
        echo "OK"
        return 0
    fi
}

opt_portping=yes

case $1 in
    -p|--portping)
        opt_portping=yes; shift;;
    -P|--no-portping)
        opt_portping=no; shift;;
    -h|--help)
        echo "Usage: $0 [-p|-P] HOSTNAME1 [HOSTNAME2[...]] "
        exit 0
        ;;
esac

errors=0
for h in "$@"
do
    run_all_pings $h || (let errors++ && true)
done

exit $(( errors != 0 ))
