#!/bin/sh

if [ $# -eq 1 ]
then
case $1 in
-h|--help)
    echo "${0##*/}: Synonymous to 'uniq -c', but counts to the right, commna separated"
    exit 0
    ;;
esac
fi

uniq -c "$@" |  sed -e 's/^ *\([0-9]*\) \(.*\)$/\2,\1/g'
