#!/usr/bin/python
import sys
import urllib

if len(sys.argv) > 1:
    for arg in sys.argv[1:]:
        print urllib.unquote_plus(arg)
else:
    for line in sys.stdin.readlines():
        print urllib.unquote_plus(line)
