#!/usr/bin/python
import sys
import urllib

if len(sys.argv) > 1:
    for arg in sys.argv[1:]:
        sys.stdout.write(urllib.unquote_plus(arg))
else:
    for line in sys.stdin.readlines():
        sys.stdout.write(urllib.unquote_plus(line))
