#!/usr/bin/env python
import sys

try:
    from urllib.parse import quote_plus
except ImportError:
    # try Python2 version
    from urllib import quote_plus

try:
    if len(sys.argv) > 1:
        for arg in sys.argv[1:]:
            sys.stdout.write(quote_plus(arg))
    else:
        line = sys.stdin.readline()
        while line:
            sys.stdout.write(quote_plus(line))
            line = sys.stdin.readline()
except KeyboardInterrupt:
    sys.exit(0)
except IOError as e:
    import errno
    if e.errno == errno.EPIPE:
        sys.exit(0)
    else:
        raise
